---
- name: Add PostgreSQL repository signing key.
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository.
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present

- name: Install PostgreSQL client.
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - postgresql-client-10
