---
- name: Add PostgreSQL repository signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  tags:
    - always

- name: Add Debian 8 PostgreSQL repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
    state: present
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'
  tags:
    - always

- name: Add Debian 9 PostgreSQL repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
    state: present
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'
  tags:
    - always

- name: Add Ubuntu 16.04 LTS PostgreSQL repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
  tags:
    - always

- name: Install PostgreSQL client
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - postgresql-client-10
  tags:
    - always
