---
- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
    enabled: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
