- name: Perform database version check.
  shell: >
    PGPASSWORD={{ pg_password }} psql -h {{ pg_hostname }} -p {{ pg_port }} -d {{ pg_database }} -U {{ pg_username }} -t -c "SELECT version FROM sdg.db_settings LIMIT 1;"
  register: db_version

- name: Get latest migration version.
  shell: >
    ls [0-9]* | sort -rn | head -1 | awk '{printf "%d", $1}'
  register: migration_version
  args:
    chdir: "{{ project_root }}"

- debug:
    msg: "The database version is {{ db_version.stdout_lines }} and the migration version is {{ migration_version.stdout_lines }}"
