---
- name: Add Debian Jessie backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    state: present
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'
  tags:
    - always

- name: Add Debian Stretch backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main
    state: present
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'
  tags:
    - always
